networks:
  my_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    volumes:
      - redis_data:/data
    restart: always
  
volumes:
  redis_data:
    driver: local